import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "ShopCenter",
    description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "/lws-logo.svg", // /public path
                href: "/lws-logo.svg", // /public path
            },
        ],
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
